[package]
name = "midstring"
version = "0.1.0"
edition = "2021"
description = "Create a string between two other strings, that is lexicographically halfway between them."
license = "MIT"


[dependencies]
